version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 3
    groups:
      all-dependencies:
        patterns:
          - "*"
    ignore:
      # For all deps
      - dependency-name: "*"
        # ignore all major updates
        update-types: ["version-update:semver-major"]
